//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapExample.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int Id { get; set; }
        public int AutorId { get; set; }
        public string Titulo { get; set; }
        public string Isbn { get; set; }
        public string Sinopsis { get; set; }
        public string Descripcion { get; set; }
        public string UrlImagen { get; set; }
    
        public virtual Autor Autor { get; set; }
    }
}
